### ISSUE TITLE
Compare and select an LLM model to use

### ISSUE THREAD

**Issue by KubaPawlak** [MagdalenaPakula/StudentReportLLM#3]
# Overview
Come up with a list of LLM models that can be used with the project and choose the most suitable one.

# Tasks
- [x] Create a list of LLM models to consider (see [current candidates](#current-candidates))
- [x] Come up with a list of comparison criteria that will guide the model selection
- [x] Test the chosen models and create a summary of their performance
- [x] Create a file in the `docs` folder, documenting the testing and selection process, along with the model comparison.
- [x] Document the usage of the model's API

# Current candidates
- BERT
- T5
- LLaMA-2
- Mistral
