### ISSUE TITLE
Instrument the application with log and metric collection

### ISSUE THREAD

**Issue by KubaPawlak** [MagdalenaPakula/StudentReportLLM#9]
# Overview
The application should be set up to collect metrics and sending logs to a remote server.

# Tasks
## General
- [x] Set up opentelemetry collector in docker compose
## Logs
- [x] Set up elasticsearch for storing logs
- [x] Set up log dashboard (Kibana)
- [x] Set up opentelemetry collector to send logs to elasticsearch
- [x] Configure logging in the services to send logs to the collector
## Metrics
- [x] Set up Prometheus in the docker compose for storing and querying metrics
- [x] Configure opentelemetry collector to send service metrics to Prometheus
- [x] (Optional) Send collector's internal metrics to Prometheus
- [x] Add metrics collection to the services
- [ ] Add Grafana to docker compose
- [ ] Setup metrics dashboards in Grafana

# Notes
1. Although this issue is not related to the CI/CD pipeline itself, it influences the CI/CD grade, so it received the CI/CD label.

**Comment by KubaPawlak** [comment]
Nie będziemy robić Grafany, bo nie ma tego w wymaganiach, a tak po prostu sztuka dla sztuki mi się nie chce.
